# Generated by Django 4.2.4 on 2023-08-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motorcycle',
            options={'ordering': ['id'], 'verbose_name': 'Мотоциклы', 'verbose_name_plural': 'Мотоциклы'},
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='content',
            field=models.TextField(blank=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
